version: '3'
services:
  backend:
    build: ./backend  
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - ./backend/.env  

  frontend:
    build: ./frontend  
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
